[package]
name = "mathai-accessibility"
version = "0.1.0"
edition = "2024"
license = "0BSD"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.128"
mathcat = { version = "=0.7.6-rc.3", features = ["include-zip"] }

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
panic = "abort"
